//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Nester.Admin
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum AppServiceSubscriptionStatus : int
	{
		active = 0,
		inactive = 1,
		stopped = 3,
		started = 3,
	}
}
