//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Nester.Admin
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Newtonsoft.Json;

    public class AppServiceTier : Cloud.ManagedEntity
    {
        private Int64 _id;
        private Int64 _appServiceId;
        private string _tag;
        private string _name;
        private string _type;
        private string _period;
        private decimal _itemCost;
        private string _featuresIncluded;
        private AppService _service = null;

        public AppServiceTier() 
            : base("app_service_tier")
        {
        }

        [JsonIgnore]
        public Admin.AppService Service
        {
            get { return _service; }
            set { SetProperty(ref _service, value); }
        }

        public override string Key
        {
            get { return _id.ToString(); }
        }

        override public string Collection
        {
            get
            {
                if (_service != null)
                {
                    return _service.CollectionKey + base.Collection;
                }
                else
                {
                    return base.Collection;
                }
            }
        }

        override public string CollectionKey
        {
            get
            {
                if (_service != null)
                {
                    return _service.CollectionKey + base.CollectionKey;
                }
                else
                {
                    return base.CollectionKey;
                }
            }
        }

        [JsonProperty("id")]
        public Int64 Id
        {
            get { return _id; }
            set { _id = value; }
        }

        [JsonProperty("app_service_id")]
        public Int64 AppServiceId
        {
            get { return _appServiceId; }
            set { _appServiceId = value; }
        }

        [JsonProperty("tag")]
        public string Tag
        {
            get { return _tag; }
            set { SetProperty(ref _tag, value); }
        }

        [JsonProperty("name")]
        public string Name
        {
            get { return _name; }
            set { SetProperty(ref _name, value); }
        }

        [JsonProperty("type")]
        public string Type
        {
            get { return _type; }
            set { SetProperty(ref _type, value); }
        }

        [JsonProperty("period")]
        public string Period
        {
            get { return _period; }
            set { SetProperty(ref _period, value); }
        }

        [JsonProperty("item_cost")]
        public decimal ItemCost
        {
            get { return _itemCost; }
            set { SetProperty(ref _itemCost, value); }
        }

        [JsonProperty("features_included")]
        public string FeaturesIncluded
        {
            get { return _featuresIncluded; }
            set { SetProperty(ref _featuresIncluded, value); }
        }

        public string[] FeaturesIncludedArray
        {
            get
            {
                List<string> values = JsonConvert.DeserializeObject<List<string>>(
                    _featuresIncluded);
                return values.ToArray<string>();
            }
        }
    }
}

