//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Nester.Admin
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum AppStatus : int
	{
		init = 0,
		assigned = 1,
		updating = 3,
		deployed = 2,
		removed = 4,
	} 
}
