//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Nester.Admin
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Newtonsoft.Json;

    public class AppServiceSubscription : Cloud.ManagedEntity
    {
        private Int64 _id;
        private Int64 _appId;
        private Int64 _appServiceTierId;
        private string _status;
        private App _application = null;
        private AppServiceTier _serviceTier = null;

        public AppServiceSubscription()
            : base("app_service_subscription")
        {
        }

        [JsonIgnore]
        public Admin.App App
        {
            get { return _application; }
            set {
                _application = value;
                this.AppId = _application.Id;
            }
        }

        public Admin.AppServiceTier ServiceTier
        {
            get { return _serviceTier; }
            set { _serviceTier = value; }
        }

        public override string Key
        {
            get { return _id.ToString(); }
        }

        override public string Collection
        {
            get
            {
                if (_application != null)
                {
                    return _application.CollectionKey + base.Collection;
                }
                else
                {
                    return base.Collection;
                }
            }
        }

        override public string CollectionKey
        {
            get
            {
                if (_application != null)
                {
                    return _application.CollectionKey + base.CollectionKey;
                }
                else
                {
                    return base.CollectionKey;
                }
            }
        }

        [JsonProperty("id")]
        public Int64 Id
        {
            get { return _id; }
            set { _id = value; }
        }

        [JsonProperty("app_id")]
        public Int64 AppId
		{
            get { return _appId; }
            set { SetProperty(ref _appId, value); }
        }

        [JsonProperty("app_service_tier_id")]
        public Int64 AppServiceTierId
		{
            get { return _appServiceTierId; }
            set { SetProperty(ref _appServiceTierId, value); }
        }
 
        [JsonProperty("status")]
        public string Status
		{
            get { return _status; }
            set { SetProperty(ref _status, value); }
        }
    }
}

