//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Nester.Auth
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Newtonsoft.Json;

    /*
     * Cloud objects needed for the app
     * will loaded as used and a reference
     * will be kept here.  The idea is only
     * loading objects as needed given small
     * device constraints.  The server is
     * also only contacted per object per 
     * session. The object is kept cached
     * locally within a single session.
     */

    public class Permit : Cloud.ManagedEntity
    {
        private string _token = "<-token->";
        private string _password = null;
        private string _securityCode = null;
        private Admin.User _user;

        public Permit() 
            : base("permit")
        {
        }

        public override string Key
        {
            get { return _user.Email; }
        }

        [JsonProperty("token")]
        public string Token
        {
            get { return _token; }
            set { _token = value; }
        }

        public string Password
        {
            get { return _password; }
            set { _password = value; }
        }

        public string SecurityCode
        {
            get { return _securityCode; }
            set { _securityCode = value; }
        }

        [JsonProperty("owner")]
        public Admin.User Owner
        {
            get { return _user; }
            set { SetProperty(ref _user, value); }
        }
    }
}

